name: Build

on:
  workflow_call:
    inputs:
      secrets_env:
        required: true
        type: string
      app_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', inputs.secrets_env)] }}
          aws-secret-access-key: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', inputs.secrets_env)] }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - run: |
          npm ci --no-fund

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ fromJSON(secrets[format('{0}_ECR', inputs.secrets_env)]).app }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          ls -l
          echo ECR_REGISTRY:IMAGE_TAG $ECR_REGISTRY:$IMAGE_TAG
           docker build --build-arg APP_NAME=${{ inputs.app_name }} \
            -t $ECR_REGISTRY:$IMAGE_TAG .
          docker push $ECR_REGISTRY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "::set-output name=image::$ECR_REGISTRY:$IMAGE_TAG"
        shell: bash
      - name: Download task definition
        env:
          TASK_DEFINITION_FAMILY: ${{ secrets[format('{0}_TASK_DEFINITION_FAMILY_{1}', inputs.secrets_env, inputs.app_name)] }}

        run: |
          aws ecs describe-task-definition --task-definition $TASK_DEFINITION_FAMILY --query taskDefinition | jq -r 'del(
            .taskDefinitionArn,
            .requiresAttributes,
            .compatibilities,
            .revision,
            .status,
            .registeredAt,
            .registeredBy
          )' > task-definition.json
        shell: bash
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.app_name }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets[format('{0}_SERVICE_{1}', inputs.secrets_env, inputs.app_name)] }}
          cluster: ${{ secrets[format('{0}_ECS_CLUSTER', inputs.secrets_env)] }}
          wait-for-service-stability: true
